---
apiVersion: example.com/v1aplha1
kind: SecretMap
metadata:
  name: aws-example
spec:
  secretName: aws-example
  labels:
    app.kubernetes.io/component: database
  mappings:
    DB_PASSWORD:
      aws:
        store: ssmParameterStore
        name: /app/hello-world/db/password
        region: ap-southeast-2
