---
apiVersion: example.com/v1aplha1
kind: SecretMap
metadata:
  name: static-example-overwrite
spec:
  secretName: existing
  secretAlreadyExists:
    matchLabels:
      kube-secrets-map.example.com/overwrite: "true"
  mappings:
    DB_USERNAME:
      static: postgres
