---
apiVersion: example.com/v1aplha1
kind: SecretMap
metadata:
  name: static-example
spec:
  secretName: static-example
  labels:
    app.kubernetes.io/component: database
  mappings:
    DB_USERNAME:
      static: postgres
