---
# Binding the role to the account in default
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretmap-controller-binding
subjects:
- kind: ServiceAccount
  namespace: default
  name: secretmap-controller
roleRef:
  kind: ClusterRole
  name: control-secretmaps
  apiGroup: rbac.authorization.k8s.io
