---
# Main deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretmap-controller
  namespace: default
  labels:
    app: secretmap-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretmap-controller
  template:
    metadata:
      labels:
        app: secretmap-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: secretmap-controller
      containers:
      - name: secretmap-controller
        image: secretmap/controller:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        # We are pointing to tempo or grafana tracing agent's otlp grpc receiver port
        - name: OPENTELEMETRY_ENDPOINT_URL
          value: "https://promstack-tempo.monitoring.svc.cluster.local:4317"
        - name: RUST_LOG
          value: "info,kube=debug,controller=debug"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
