[package]
name = "crd"
version = "0.1.0"
edition = "2021"

[dependencies]
k8s-openapi = { version = "0.15", default-features = false, features = ["v1_24"] }
kube = { version = "0.73.0", default-features = true, features = ["derive"] }
schemars = "0.8.8"
serde = "1"
serde_json = "1.0"
